version: 0.0
os: linux
files:
  - source: .
    destination: /landing-page/
hooks:
  BeforeInstall:
    - location: pre.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: setup.sh
      timeout: 300
      runas: root
