name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build & Zip the Files
        run: |
          npm install
          npm run build
          mkdir bin
          zip bin/deploy.zip appspec.yml pre.sh -r landing-page
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Store binary in S3 bucket
        run: aws s3 sync ./bin/ s3://${{ secrets.BUCKET_NAME }}/landing-page --delete
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name LandingPage \
            --deployment-group-name DevelopmentGroup \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --s3-location bucket=${{ secrets.BUCKET_NAME }},key=landing-page/deploy.zip,bundleType=zip
